language: node_js
node_js:
  - "12"
before_deploy:
  - npm run build
deploy:
  provider: s3
  access_key_id: AKIAUWTGZJ4AECYSUNP4
  secret_access_key:
    secure: SzOow2rq9NgHtXpHCncC40d564j0vCUGnPG3IyFaCRUHjp9BuIjXArs7xZ4Eo1ru7iAwiuVzS3xMjUyy3jl4yKbRUtqMnPIRB1oX89TxZYyunCeblpulTa05cEJtYjqK0FX4F03Nfzl6c6feWnXjXvIX+fGZrLczLDbbFVlKRfkCo73fhjIErJh5Vd1jW/Sevr+rMoe7cl0j6C3XLlbkci3r+0dmkna97DI2b/XjNRwm+msMC1GMEsjgx8XyQkNL9I0thyM7a2iFZh1VfdfUsejkWWPdCqU4AEgKV8flSflQ5FQ4sUl6SLRdl4PmmrtVuuv0mVQhSZ2p19yQz/RjAXz9yEsIB8QyLsrNrX45Nf/UTE9ntQp5T+AuDIdmyhEfCVsOg41G41aYSit55Xj7jmiBx9q8jmUGisSPIDZbAr58PnH5McCt3bTCSWayrNyAaAFvUcnC0C6uq2lRRHbvnhiE7LMjAIIVagcEdIkT+qyzofBXPHw1wkjteyFXxHGMHelb0H8W/LxV7cucjYig4Jg7+n/EcHeb11vWiVtB4FlFg4SCwudlFHlHmySiHF6+zJsur2L3ictOqXjtwd4A6tOdbinlO0wFALuQk48FCQMOiM5YQZkeSAkBv8JKZ4ojmTYh4Rh0nhPzI9zC7AUC97bOAVIQ/aausA5nq8zKIKM=
  bucket: etopiei.com
  local-dir: public
  acl: public_read
  skip_cleanup: true
  on:
    repo: etopiei/website
